<?xml version="1.0" encoding="US-ASCII" standalone="yes"?>
<!DOCTYPE stationlist [
<!ELEMENT stationlist (station+)>
<!ATTLIST stationlist
  created	CDATA	#REQUIRED
>

<!ELEMENT station (comp+)>
<!ATTLIST station
  code		CDATA 			#REQUIRED
  name		CDATA 			#REQUIRED
  insttype	CDATA 			#REQUIRED
  lat		CDATA 			#REQUIRED
  lon		CDATA 			#REQUIRED
  source	(SCSN|CDMG|NSMP) 	'SCSN'
  commtype	(DIG|ANA) 		'DIG'
>

<!ELEMENT comp (acc,vel,psa*)>
<!ATTLIST comp
  name          CDATA  #REQUIRED
  originalname  CDATA  #IMPLIED
>

<!ELEMENT acc EMPTY>
<!ELEMENT vel EMPTY>
<!ELEMENT psa03 EMPTY>
<!ELEMENT psa10 EMPTY>
<!ELEMENT psa30 EMPTY>
<!ATTLIST acc
  value  CDATA         #REQUIRED
  flag   CDATA        ''
>
<!ATTLIST vel
  value CDATA          #REQUIRED
  flag  CDATA         ''
>
<!ATTLIST psa03
  value CDATA          #REQUIRED
  flag  CDATA         ''
>
<!ATTLIST psa10
  value CDATA          #REQUIRED
  flag  CDATA         ''
>
<!ATTLIST psa30
  value CDATA          #REQUIRED
  flag  CDATA         ''
>
]>
<stationlist created="982348866">
<station code="AGA" name="Agave Hill" insttype="TriNet" lat="33.63838" lon="-116.4011" source="SCSN and TriNet" commtype="DIG">
<comp name="HHE">
<acc value="0.0027" flag="0" />
<vel value="0.0005" flag="0" />
<psa03 value="0.0010" flag="0" />
<psa10 value="0.0008" flag="0" />
<psa30 value="0.0001" flag="0" />
</comp>
<comp name="HHN">
<acc value="0.0021" flag="0" />
<vel value="0.0004" flag="0" />
<psa03 value="0.0012" flag="0" />
<psa10 value="0.0007" flag="0" />
<psa30 value="0.0001" flag="0" />
</comp>
<comp name="HHZ">
<acc value="0.0031" flag="0" />
<vel value="0.0005" flag="0" />
<psa03 value="0.0012" flag="0" />
<psa10 value="0.0007" flag="0" />
<psa30 value="0.0001" flag="0" />
</comp>
</station>
<station code="AGO" name="AGOURA" insttype="TriNet" lat="34.14647" lon="-118.76699" source="SCSN and TriNet" commtype="DIG">
<comp name="HLE">
<acc value="0.0858" flag="G" />
<vel value="0.0244" flag="G" />
<psa03 value="0.1226" flag="G" />
<psa10 value="0.0225" flag="G" />
<psa30 value="0.0010" flag="G" />
</comp>
<comp name="HLN">
<acc value="0.1016" flag="G" />
<vel value="0.0217" flag="G" />
<psa03 value="0.0943" flag="G" />
<psa10 value="0.0191" flag="G" />
<psa30 value="0.0013" flag="G" />
</comp>
<comp name="HLZ">
<acc value="0.0602" flag="G" />
<vel value="0.0177" flag="G" />
<psa03 value="0.0657" flag="G" />
<psa10 value="0.0117" flag="G" />
<psa30 value="0.0007" flag="G" />
</comp>
</station>
<station code="ALP" name="ANTELOPE" insttype="TriNet" lat="34.68708" lon="-118.29946" source="SCSN and TriNet" commtype="DIG">
<comp name="HHE">
<acc value="0.1065" flag="0" />
<vel value="0.0481" flag="0" />
<psa03 value="0.2006" flag="0" />
<psa10 value="0.0595" flag="0" />
<psa30 value="0.0020" flag="0" />
</comp>
<comp name="HHN">
<acc value="0.1494" flag="0" />
<vel value="0.0647" flag="0" />
<psa03 value="0.2744" flag="0" />
<psa10 value="0.0357" flag="0" />
<psa30 value="0.0025" flag="0" />
</comp>
<comp name="HHZ">
<acc value="0.1213" flag="0" />
<vel value="0.0295" flag="0" />
<psa03 value="0.1650" flag="0" />
<psa10 value="0.0172" flag="0" />
<psa30 value="0.0012" flag="0" />
</comp>
</station>
<station code="BAK" name="CALSTATE BAKERSFIELD" insttype="TriNet" lat="35.34413" lon="-119.1043" source="SCSN and TriNet" commtype="DIG">
<comp name="HHE">
<acc value="0.0400" flag="0" />
<vel value="0.0170" flag="0" />
<psa03 value="0.1076" flag="0" />
<psa10 value="0.0098" flag="0" />
<psa30 value="0.0012" flag="0" />
</comp>
<comp name="HHN">
<acc value="0.0324" flag="0" />
<vel value="0.0116" flag="0" />
<psa03 value="0.0803" flag="0" />
<psa10 value="0.0080" flag="0" />
<psa30 value="0.0017" flag="0" />
</comp>
<comp name="HHZ">
<acc value="0.0227" flag="0" />
<vel value="0.0075" flag="0" />
<psa03 value="0.0608" flag="0" />
<psa10 value="0.0076" flag="0" />
<psa30 value="0.0015" flag="0" />
</comp>
</station>
<station code="BAR" name="BARRETT" insttype="TriNet" lat="32.68005" lon="-116.67215" source="SCSN and TriNet" commtype="DIG">
<comp name="HHE">
<acc value="0.0015" flag="0" />
<vel value="0.0004" flag="0" />
<psa03 value="0.0018" flag="0" />
<psa10 value="0.0002" flag="0" />
<psa30 value="0.0001" flag="0" />
</comp>
<comp name="HHN">
<acc value="0.0014" flag="0" />
<vel value="0.0004" flag="0" />
<psa03 value="0.0012" flag="0" />
<psa10 value="0.0002" flag="0" />
<psa30 value="0.0000" flag="0" />
</comp>
<comp name="HHZ">
<acc value="0.0009" flag="0" />
<vel value="0.0004" flag="0" />
<psa03 value="0.0009" flag="0" />
<psa10 value="0.0002" flag="0" />
<psa30 value="0.0000" flag="0" />
</comp>
</station>
<station code="BBA" name="BURBANK AIRPORT" insttype="TriNet" lat="34.19551" lon="-118.3534" source="SCSN and TriNet" commtype="DIG">
<comp name="HLE">
<acc value="0.0667" flag="G" />
<vel value="0.0142" flag="G" />
<psa03 value="0.0563" flag="G" />
<psa10 value="0.0144" flag="G" />
<psa30 value="0.0019" flag="G" />
</comp>
<comp name="HLN">
<acc value="0.0725" flag="G" />
<vel value="0.0163" flag="G" />
<psa03 value="0.0422" flag="G" />
<psa10 value="0.0113" flag="G" />
<psa30 value="0.0012" flag="G" />
</comp>
<comp name="HLZ">
<acc value="0.1083" flag="G" />
<vel value="0.0148" flag="G" />
<psa03 value="0.0372" flag="G" />
<psa10 value="0.0071" flag="G" />
<psa30 value="0.0008" flag="G" />
</comp>
</station>
<station code="BBB" name="BOMBAY BEACH" insttype="TriNet" lat="33.35262" lon="-115.73325" source="SCSN and TriNet" commtype="DIG">
<comp name="HLE">
<acc value="0.0215" flag="G" />
<vel value="0.0058" flag="G" />
<psa03 value="0.0366" flag="G" />
<psa10 value="0.0019" flag="G" />
<psa30 value="0.0005" flag="G" />
</comp>
<comp name="HLN">
<acc value="0.0290" flag="G" />
<vel value="0.0097" flag="G" />
<psa03 value="0.0641" flag="G" />
<psa10 value="0.0020" flag="G" />
<psa30 value="0.0006" flag="G" />
</comp>
<comp name="HLZ">
<acc value="0.0278" flag="G" />
<vel value="0.0067" flag="G" />
<psa03 value="0.0528" flag="G" />
<psa10 value="0.0022" flag="G" />
<psa30 value="0.0005" flag="G" />
</comp>
</station>
<station code="BBR" name="Big Bear Solar Observatory" insttype="TriNet" lat="34.2623" lon="-116.92075" source="SCSN and TriNet" commtype="DIG">
<comp name="HHE">
<acc value="0.0052" flag="0" />
<vel value="0.0039" flag="0" />
<psa03 value="0.0095" flag="0" />
<psa10 value="0.0083" flag="0" />
<psa30 value="0.0003" flag="0" />
</comp>
<comp name="HHN">
<acc value="0.0057" flag="0" />
<vel value="0.0040" flag="0" />
<psa03 value="0.0121" flag="0" />
<psa10 value="0.0093" flag="0" />
<psa30 value="0.0004" flag="0" />
</comp>
<comp name="HHZ">
<acc value="0.0040" flag="0" />
<vel value="0.0026" flag="0" />
<psa03 value="0.0057" flag="0" />
<psa10 value="0.0042" flag="0" />
<psa30 value="0.0003" flag="0" />
</comp>
</station>
<station code="BC3" name="BIG CHUCKAWALLA MTNS" insttype="TriNet" lat="33.6548" lon="-115.4531" source="SCSN and TriNet" commtype="DIG">
<comp name="HHE">
<acc value="0.0002" flag="0" />
<vel value="0.0002" flag="0" />
<psa03 value="0.0004" flag="0" />
<psa10 value="0.0002" flag="0" />
<psa30 value="0.0000" flag="0" />
</comp>
<comp name="HHN">
<acc value="0.0003" flag="0" />
<vel value="0.0002" flag="0" />
<psa03 value="0.0005" flag="0" />
<psa10 value="0.0001" flag="0" />
<psa30 value="0.0000" flag="0" />
</comp>
<comp name="HHZ">
<acc value="0.0003" flag="0" />
<vel value="0.0002" flag="0" />
<psa03 value="0.0004" flag="0" />
<psa10 value="0.0002" flag="0" />
<psa30 value="0.0000" flag="0" />
</comp>
</station>
<station code="BKR" name="BAKER" insttype="TriNet" lat="35.2693" lon="-116.0703" source="SCSN and TriNet" commtype="DIG">
<comp name="HHE">
<acc value="0.0063" flag="0" />
<vel value="0.0026" flag="0" />
<psa03 value="0.0063" flag="0" />
<psa10 value="0.0039" flag="0" />
<psa30 value="0.0002" flag="0" />
</comp>
<comp name="HHN">
<acc value="0.0060" flag="0" />
<vel value="0.0037" flag="0" />
<psa03 value="0.0109" flag="0" />
<psa10 value="0.0029" flag="0" />
<psa30 value="0.0002" flag="0" />
</comp>
<comp name="HHZ">
<acc value="0.0103" flag="0" />
<vel value="0.0017" flag="0" />
<psa03 value="0.0053" flag="0" />
<psa10 value="0.0023" flag="0" />
<psa30 value="0.0002" flag="0" />
</comp>
</station>
<station code="BLA" name="BlackRock Canyon Campground" insttype="TriNet" lat="34.0697" lon="-116.3889" source="SCSN and TriNet" commtype="DIG">
<comp name="HHE">
<acc value="0.0021" flag="0" />
<vel value="0.0009" flag="0" />
<psa03 value="0.0020" flag="0" />
<psa10 value="0.0014" flag="0" />
<psa30 value="0.0002" flag="0" />
</comp>
<comp name="HHN">
<acc value="0.0020" flag="0" />
<vel value="0.0014" flag="0" />
<psa03 value="0.0028" flag="0" />
<psa10 value="0.0018" flag="0" />
<psa30 value="0.0001" flag="0" />
</comp>
<comp name="HHZ">
<acc value="0.0020" flag="0" />
<vel value="0.0008" flag="0" />
<psa03 value="0.0015" flag="0" />
<psa10 value="0.0014" flag="0" />
<psa30 value="0.0001" flag="0" />
</comp>
</station>
<station code="BTC" name="BRUNTS CORNER" insttype="TriNet" lat="33.01255" lon="-115.21993" source="SCSN and TriNet" commtype="DIG">
<comp name="HHE">
<acc value="0.0019" flag="0" />
<vel value="0.0005" flag="0" />
<psa03 value="0.0003" flag="0" />
<psa10 value="0.0002" flag="0" />
<psa30 value="0.0001" flag="0" />
</comp>
<comp name="HHN">
<acc value="0.0022" flag="0" />
<vel value="0.0007" flag="0" />
<psa03 value="0.0003" flag="0" />
<psa10 value="0.0002" flag="0" />
<psa30 value="0.0001" flag="0" />
</comp>
<comp name="HHZ">
<acc value="0.0035" flag="0" />
<vel value="0.0004" flag="0" />
<psa03 value="0.0004" flag="0" />
<psa10 value="0.0001" flag="0" />
<psa30 value="0.0000" flag="0" />
</comp>
</station>
<station code="BTP" name="BURNT PEAK" insttype="TriNet" lat="34.6817" lon="-118.5738" source="SCSN and TriNet" commtype="DIG">
<comp name="HHE">
<acc value="0.1573" flag="0" />
<vel value="0.0506" flag="0" />
<psa03 value="0.2878" flag="0" />
<psa10 value="0.0228" flag="0" />
<psa30 value="0.0017" flag="0" />
</comp>
<comp name="HHN">
<acc value="0.1660" flag="0" />
<vel value="0.0581" flag="0" />
<psa03 value="0.3434" flag="0" />
<psa10 value="0.0474" flag="0" />
<psa30 value="0.0024" flag="0" />
</comp>
<comp name="HHZ">
<acc value="0.1161" flag="0" />
<vel value="0.0248" flag="0" />
<psa03 value="0.0787" flag="0" />
<psa10 value="0.0121" flag="0" />
<psa30 value="0.0008" flag="0" />
</comp>
</station>
<station code="BVH" name="BEVERLY HILLS" insttype="TriNet" lat="34.07618" lon="-118.3959" source="SCSN and TriNet" commtype="DIG">
<comp name="HLE">
<acc value="0.0312" flag="G" />
<vel value="0.0131" flag="G" />
<psa03 value="0.0306" flag="G" />
<psa10 value="0.0177" flag="G" />
<psa30 value="0.0017" flag="G" />
</comp>
<comp name="HLN">
<acc value="0.0532" flag="G" />
<vel value="0.0143" flag="G" />
<psa03 value="0.0349" flag="G" />
<psa10 value="0.0133" flag="G" />
<psa30 value="0.0008" flag="G" />
</comp>
<comp name="HLZ">
<acc value="0.0225" flag="G" />
<vel value="0.0075" flag="G" />
<psa03 value="0.0136" flag="G" />
<psa10 value="0.0082" flag="G" />
<psa30 value="0.0010" flag="G" />
</comp>
</station>
<station code="CHF" name="CHILAO FLAT RNGR STA" insttype="TriNet" lat="34.3334" lon="-118.0259" source="SCSN and TriNet" commtype="DIG">
<comp name="HHE">
<acc value="0.0300" flag="0" />
<vel value="0.0064" flag="0" />
<psa03 value="0.0154" flag="0" />
<psa10 value="0.0066" flag="0" />
<psa30 value="0.0003" flag="0" />
</comp>
<comp name="HHN">
<acc value="0.0302" flag="0" />
<vel value="0.0061" flag="0" />
<psa03 value="0.0182" flag="0" />
<psa10 value="0.0039" flag="0" />
<psa30 value="0.0002" flag="0" />
</comp>
<comp name="HHZ">
<acc value="0.0122" flag="0" />
<vel value="0.0045" flag="0" />
<psa03 value="0.0092" flag="0" />
<psa10 value="0.0054" flag="0" />
<psa30 value="0.0003" flag="0" />
</comp>
</station>
<station code="CHN" name="Chino" insttype="TriNet" lat="33.99879" lon="-117.68044" source="SCSN and TriNet" commtype="DIG">
<comp name="HHE">
<acc value="0.0131" flag="0" />
<vel value="0.0071" flag="0" />
<psa03 value="0.0260" flag="0" />
<psa10 value="0.0085" flag="0" />
<psa30 value="0.0006" flag="0" />
</comp>
<comp name="HHN">
<acc value="0.0133" flag="0" />
<vel value="0.0075" flag="0" />
<psa03 value="0.0232" flag="0" />
<psa10 value="0.0076" flag="0" />
<psa30 value="0.0006" flag="0" />
</comp>
<comp name="HHZ">
<acc value="0.0219" flag="0" />
<vel value="0.0030" flag="0" />
<psa03 value="0.0089" flag="0" />
<psa10 value="0.0031" flag="0" />
<psa30 value="0.0001" flag="0" />
</comp>
</station>
<station code="CIA" name="CATALINA ISL AIRPORT" insttype="TriNet" lat="33.402" lon="-118.4152" source="SCSN and TriNet" commtype="DIG">
<comp name="HHE">
<acc value="0.0163" flag="0" />
<vel value="0.0051" flag="0" />
<psa03 value="0.0150" flag="0" />
<psa10 value="0.0044" flag="0" />
<psa30 value="0.0003" flag="0" />
</comp>
<comp name="HHN">
<acc value="0.0162" flag="0" />
<vel value="0.0050" flag="0" />
<psa03 value="0.0198" flag="0" />
<psa10 value="0.0023" flag="0" />
<psa30 value="0.0002" flag="0" />
</comp>
<comp name="HHZ">
<acc value="0.0108" flag="0" />
<vel value="0.0029" flag="0" />
<psa03 value="0.0112" flag="0" />
<psa10 value="0.0021" flag="0" />
<psa30 value="0.0002" flag="0" />
</comp>
</station>
<station code="CLC" name="CHINA LAKE" insttype="TriNet" lat="35.81574" lon="-117.59751" source="SCSN and TriNet" commtype="DIG">
<comp name="HHE">
<acc value="0.0020" flag="0" />
<vel value="0.0021" flag="0" />
<psa03 value="0.0072" flag="0" />
<psa10 value="0.0030" flag="0" />
<psa30 value="0.0002" flag="0" />
</comp>
<comp name="HHN">
<acc value="0.0027" flag="0" />
<vel value="0.0019" flag="0" />
<psa03 value="0.0054" flag="0" />
<psa10 value="0.0026" flag="0" />
<psa30 value="0.0004" flag="0" />
</comp>
<comp name="HHZ">
<acc value="0.0021" flag="0" />
<vel value="0.0031" flag="0" />
<psa03 value="0.0053" flag="0" />
<psa10 value="0.0053" flag="0" />
<psa30 value="0.0005" flag="0" />
</comp>
</station>
<station code="CLT" name="CALECTRIC" insttype="TriNet" lat="34.09316" lon="-117.31671" source="SCSN and TriNet" commtype="DIG">
<comp name="HHE">
<acc value="0.0201" flag="0" />
<vel value="0.0083" flag="0" />
<psa03 value="0.0514" flag="0" />
<psa10 value="0.0133" flag="0" />
<psa30 value="0.0008" flag="0" />
</comp>
<comp name="HHN">
<acc value="0.0168" flag="0" />
<vel value="0.0078" flag="0" />
<psa03 value="0.0553" flag="0" />
<psa10 value="0.0101" flag="0" />
<psa30 value="0.0007" flag="0" />
</comp>
<comp name="HHZ">
<acc value="0.0216" flag="0" />
<vel value="0.0046" flag="0" />
<psa03 value="0.0172" flag="0" />
<psa10 value="0.0103" flag="0" />
<psa30 value="0.0004" flag="0" />
</comp>
</station>
<station code="CPP" name="CAL POLY POMONA" insttype="TriNet" lat="34.0602" lon="-117.809" source="SCSN and TriNet" commtype="DIG">
<comp name="HLE">
<acc value="0.0229" flag="G" />
<vel value="0.0148" flag="G" />
<psa03 value="0.0543" flag="G" />
<psa10 value="0.0221" flag="G" />
<psa30 value="0.0009" flag="G" />
</comp>
<comp name="HLN">
<acc value="0.0336" flag="G" />
<vel value="0.0148" flag="G" />
<psa03 value="0.0569" flag="G" />
<psa10 value="0.0180" flag="G" />
<psa30 value="0.0007" flag="G" />
</comp>
<comp name="HLZ">
<acc value="0.0408" flag="G" />
<vel value="0.0053" flag="G" />
<psa03 value="0.0241" flag="G" />
<psa10 value="0.0060" flag="G" />
<psa30 value="0.0003" flag="G" />
</comp>
</station>
<station code="CRN" name="CORONA" insttype="TriNet" lat="33.87574" lon="-117.56106" source="SCSN and TriNet" commtype="DIG">
<comp name="HLE">
<acc value="0.0341" flag="G" />
<vel value="0.0063" flag="G" />
<psa03 value="0.0173" flag="G" />
<psa10 value="0.0063" flag="G" />
<psa30 value="0.0004" flag="G" />
</comp>
<comp name="HLN">
<acc value="0.0176" flag="G" />
<vel value="0.0089" flag="G" />
<psa03 value="0.0256" flag="G" />
<psa10 value="0.0062" flag="G" />
<psa30 value="0.0006" flag="G" />
</comp>
<comp name="HLZ">
<acc value="0.0579" flag="G" />
<vel value="0.0042" flag="G" />
<psa03 value="0.0154" flag="G" />
<psa10 value="0.0033" flag="G" />
<psa30 value="0.0007" flag="G" />
</comp>
</station>
<station code="CWC" name="COTTONWOOD CREEK" insttype="TriNet" lat="36.43988" lon="-118.08016" source="SCSN and TriNet" commtype="DIG">
<comp name="HHE">
<acc value="0.0062" flag="0" />
<vel value="0.0029" flag="0" />
<psa03 value="0.0211" flag="0" />
<psa10 value="0.0011" flag="0" />
<psa30 value="0.0001" flag="0" />
</comp>
<comp name="HHN">
<acc value="0.0051" flag="0" />
<vel value="0.0022" flag="0" />
<psa03 value="0.0187" flag="0" />
<psa10 value="0.0014" flag="0" />
<psa30 value="0.0001" flag="0" />
</comp>
<comp name="HHZ">
<acc value="0.0023" flag="0" />
<vel value="0.0012" flag="0" />
<psa03 value="0.0079" flag="0" />
<psa10 value="0.0010" flag="0" />
<psa30 value="0.0001" flag="0" />
</comp>
</station>
<station code="DAN" name="DANBY" insttype="TriNet" lat="34.6371" lon="-115.3805" source="SCSN and TriNet" commtype="DIG">
<comp name="HHE">
<acc value="0.0010" flag="0" />
<vel value="0.0004" flag="0" />
<psa03 value="0.0012" flag="0" />
<psa10 value="0.0004" flag="0" />
<psa30 value="0.0000" flag="0" />
</comp>
<comp name="HHN">
<acc value="0.0011" flag="0" />
<vel value="0.0004" flag="0" />
<psa03 value="0.0011" flag="0" />
<psa10 value="0.0004" flag="0" />
<psa30 value="0.0000" flag="0" />
</comp>
<comp name="HHZ">
<acc value="0.0013" flag="0" />
<vel value="0.0004" flag="0" />
<psa03 value="0.0016" flag="0" />
<psa10 value="0.0005" flag="0" />
<psa30 value="0.0000" flag="0" />
</comp>
</station>
<station code="DEV" name="DEVERS" insttype="TriNet" lat="33.935" lon="-116.577" source="SCSN and TriNet" commtype="DIG">
<comp name="HHE">
<acc value="0.0082" flag="0" />
<vel value="0.0019" flag="0" />
<psa03 value="0.0049" flag="0" />
<psa10 value="0.0026" flag="0" />
<psa30 value="0.0002" flag="0" />
</comp>
<comp name="HHN">
<acc value="0.0111" flag="0" />
<vel value="0.0023" flag="0" />
<psa03 value="0.0043" flag="0" />
<psa10 value="0.0032" flag="0" />
<psa30 value="0.0002" flag="0" />
</comp>
<comp name="HHZ">
<acc value="0.0094" flag="0" />
<vel value="0.0013" flag="0" />
<psa03 value="0.0028" flag="0" />
<psa10 value="0.0013" flag="0" />
<psa30 value="0.0002" flag="0" />
</comp>
</station>
<station code="DGR" name="DOMENIGONI RESERVOIR" insttype="TriNet" lat="33.64996" lon="-117.00948" source="SCSN and TriNet" commtype="DIG">
<comp name="HHE">
<acc value="0.0025" flag="0" />
<vel value="0.0008" flag="0" />
<psa03 value="0.0035" flag="0" />
<psa10 value="0.0007" flag="0" />
<psa30 value="0.0001" flag="0" />
</comp>
<comp name="HHN">
<acc value="0.0028" flag="0" />
<vel value="0.0008" flag="0" />
<psa03 value="0.0041" flag="0" />
<psa10 value="0.0010" flag="0" />
<psa30 value="0.0002" flag="0" />
</comp>
<comp name="HHZ">
<acc value="0.0019" flag="0" />
<vel value="0.0007" flag="0" />
<psa03 value="0.0033" flag="0" />
<psa10 value="0.0005" flag="0" />
<psa30 value="0.0001" flag="0" />
</comp>
</station>
<station code="DJJ" name="DONNA JONES JENKINS" insttype="TriNet" lat="34.1058" lon="-118.4538" source="SCSN and TriNet" commtype="DIG">
<comp name="HHE">
<acc value="0.0483" flag="0" />
<vel value="0.0222" flag="0" />
<psa03 value="0.0871" flag="0" />
<psa10 value="0.0133" flag="0" />
<psa30 value="0.0011" flag="0" />
</comp>
<comp name="HHN">
<acc value="0.0389" flag="0" />
<vel value="0.0135" flag="0" />
<psa03 value="0.0718" flag="0" />
<psa10 value="0.0060" flag="0" />
<psa30 value="0.0004" flag="0" />
</comp>
<comp name="HHZ">
<acc value="0.0335" flag="0" />
<vel value="0.0101" flag="0" />
<psa03 value="0.0417" flag="0" />
<psa10 value="0.0036" flag="0" />
<psa30 value="0.0004" flag="0" />
</comp>
</station>
<station code="DRC" name="DESERT RESEARCH CENT" insttype="TriNet" lat="32.8054" lon="-115.44654" source="SCSN and TriNet" commtype="DIG">
<comp name="HHE">
<acc value="0.0118" flag="0" />
<vel value="0.0016" flag="0" />
<psa03 value="0.0078" flag="0" />
<psa10 value="0.0003" flag="0" />
<psa30 value="0.0002" flag="0" />
</comp>
<comp name="HHN">
<acc value="0.0081" flag="0" />
<vel value="0.0019" flag="0" />
<psa03 value="0.0082" flag="0" />
<psa10 value="0.0004" flag="0" />
<psa30 value="0.0003" flag="0" />
</comp>
<comp name="HHZ">
<acc value="0.0083" flag="0" />
<vel value="0.0011" flag="0" />
<psa03 value="0.0109" flag="0" />
<psa10 value="0.0005" flag="0" />
<psa30 value="0.0001" flag="0" />
</comp>
</station>
<station code="EDW" name="EDWARDS AFB" insttype="TriNet" lat="34.88303" lon="-117.99106" source="SCSN and TriNet" commtype="DIG">
<comp name="HHE">
<acc value="0.0496" flag="0" />
<vel value="0.0125" flag="0" />
<psa03 value="0.0336" flag="0" />
<psa10 value="0.0046" flag="0" />
<psa30 value="0.0005" flag="0" />
</comp>
<comp name="HHN">
<acc value="0.0451" flag="0" />
<vel value="0.0143" flag="0" />
<psa03 value="0.0588" flag="0" />
<psa10 value="0.0099" flag="0" />
<psa30 value="0.0007" flag="0" />
</comp>
<comp name="HHZ">
<acc value="0.0232" flag="0" />
<vel value="0.0057" flag="0" />
<psa03 value="0.0125" flag="0" />
<psa10 value="0.0050" flag="0" />
<psa30 value="0.0003" flag="0" />
</comp>
</station>
<station code="ERR" name="Elmore's Ranch" insttype="TriNet" lat="33.1168" lon="-115.8227" source="SCSN and TriNet" commtype="DIG">
<comp name="HHE">
<acc value="0.0027" flag="0" />
<vel value="0.0010" flag="0" />
<psa03 value="0.0016" flag="0" />
<psa10 value="0.0005" flag="0" />
<psa30 value="0.0001" flag="0" />
</comp>
<comp name="HHN">
<acc value="0.0031" flag="0" />
<vel value="0.0012" flag="0" />
<psa03 value="0.0024" flag="0" />
<psa10 value="0.0005" flag="0" />
<psa30 value="0.0002" flag="0" />
</comp>
<comp name="HHZ">
<acc value="0.0058" flag="0" />
<vel value="0.0007" flag="0" />
<psa03 value="0.0023" flag="0" />
<psa10 value="0.0005" flag="0" />
<psa30 value="0.0001" flag="0" />
</comp>
</station>
<station code="FLL" name="FILLMORE" insttype="TriNet" lat="34.39727" lon="-118.91807" source="SCSN and TriNet" commtype="DIG">
<comp name="HLE">
<acc value="0.3736" flag="G" />
<vel value="0.1946" flag="G" />
<psa03 value="0.8304" flag="G" />
<psa10 value="0.2225" flag="G" />
<psa30 value="0.0113" flag="G" />
</comp>
<comp name="HLN">
<acc value="0.6557" flag="G" />
<vel value="0.3232" flag="G" />
<psa03 value="1.0447" flag="G" />
<psa10 value="0.3218" flag="G" />
<psa30 value="0.0237" flag="G" />
</comp>
<comp name="HLZ">
<acc value="0.3632" flag="G" />
<vel value="0.1067" flag="G" />
<psa03 value="0.3603" flag="G" />
<psa10 value="0.1494" flag="G" />
<psa30 value="0.0088" flag="G" />
</comp>
</station>
<station code="FON" name="FONTANA" insttype="TriNet" lat="34.09957" lon="-117.43876" source="SCSN and TriNet" commtype="DIG">
<comp name="HLE">
<acc value="0.0480" flag="G" />
<vel value="0.0065" flag="G" />
<psa03 value="0.0153" flag="G" />
<psa10 value="0.0049" flag="G" />
<psa30 value="0.0005" flag="G" />
</comp>
<comp name="HLN">
<acc value="0.0111" flag="G" />
<vel value="0.0066" flag="G" />
<psa03 value="0.0227" flag="G" />
<psa10 value="0.0047" flag="G" />
<psa30 value="0.0006" flag="G" />
</comp>
<comp name="HLZ">
<acc value="0.0263" flag="G" />
<vel value="0.0048" flag="G" />
<psa03 value="0.0095" flag="G" />
<psa10 value="0.0052" flag="G" />
<psa30 value="0.0004" flag="G" />
</comp>
</station>
<station code="FPC" name="FEDERAL PRISON CAMP" insttype="TriNet" lat="35.082" lon="-117.58267" source="SCSN and TriNet" commtype="DIG">
<comp name="HHE">
<acc value="0.0101" flag="0" />
<vel value="0.0034" flag="0" />
<psa03 value="0.0126" flag="0" />
<psa10 value="0.0026" flag="0" />
<psa30 value="0.0003" flag="0" />
</comp>
<comp name="HHN">
<acc value="0.0127" flag="0" />
<vel value="0.0059" flag="0" />
<psa03 value="0.0144" flag="0" />
<psa10 value="0.0060" flag="0" />
<psa30 value="0.0005" flag="0" />
</comp>
<comp name="HHZ">
<acc value="0.0061" flag="0" />
<vel value="0.0027" flag="0" />
<psa03 value="0.0052" flag="0" />
<psa10 value="0.0028" flag="0" />
<psa30 value="0.0004" flag="0" />
</comp>
</station>
<station code="FUL" name="FULLERTON" insttype="TriNet" lat="33.8717" lon="-117.92251" source="SCSN and TriNet" commtype="DIG">
<comp name="HLE">
<acc value="0.0095" flag="G" />
<vel value="0.0065" flag="G" />
<psa03 value="0.0220" flag="G" />
<psa10 value="0.0080" flag="G" />
<psa30 value="0.0011" flag="G" />
</comp>
<comp name="HLN">
<acc value="0.0145" flag="G" />
<vel value="0.0077" flag="G" />
<psa03 value="0.0287" flag="G" />
<psa10 value="0.0083" flag="G" />
<psa30 value="0.0008" flag="G" />
</comp>
<comp name="HLZ">
<acc value="0.0254" flag="G" />
<vel value="0.0053" flag="G" />
<psa03 value="0.0187" flag="G" />
<psa10 value="0.0045" flag="G" />
<psa30 value="0.0006" flag="G" />
</comp>
</station>
<station code="FUR" name="FURNACE CREEK" insttype="TriNet" lat="36.4672" lon="-116.8635" source="SCSN and TriNet" commtype="DIG">
<comp name="HHE">
<acc value="0.0045" flag="0" />
<vel value="0.0028" flag="0" />
<psa03 value="0.0038" flag="0" />
<psa10 value="0.0094" flag="0" />
<psa30 value="0.0003" flag="0" />
</comp>
<comp name="HHN">
<acc value="0.0079" flag="0" />
<vel value="0.0023" flag="0" />
<psa03 value="0.0025" flag="0" />
<psa10 value="0.0051" flag="0" />
<psa30 value="0.0003" flag="0" />
</comp>
<comp name="HHZ">
<acc value="0.0099" flag="0" />
<vel value="0.0009" flag="0" />
<psa03 value="0.0033" flag="0" />
<psa10 value="0.0013" flag="0" />
<psa30 value="0.0001" flag="0" />
</comp>
</station>
<station code="GLA" name="GLAMIS" insttype="TriNet" lat="33.052" lon="-114.827" source="SCSN and TriNet" commtype="DIG">
<comp name="HHE">
<acc value="0.0001" flag="0" />
<vel value="0.0002" flag="0" />
<psa03 value="0.0002" flag="0" />
<psa10 value="0.0002" flag="0" />
<psa30 value="0.0000" flag="0" />
</comp>
<comp name="HHN">
<acc value="0.0000" flag="0" />
<vel value="0.0001" flag="0" />
<psa03 value="0.0001" flag="0" />
<psa10 value="0.0000" flag="0" />
<psa30 value="0.0000" flag="0" />
</comp>
<comp name="HHZ">
<acc value="0.0000" flag="0" />
<vel value="0.0001" flag="0" />
<psa03 value="0.0000" flag="0" />
<psa10 value="0.0000" flag="0" />
<psa30 value="0.0000" flag="0" />
</comp>
</station>
<station code="GOR" name="GREEN OAK RANCH" insttype="TriNet" lat="33.16" lon="-117.23" source="SCSN and TriNet" commtype="DIG">
<comp name="HHE">
<acc value="0.0033" flag="0" />
<vel value="0.0007" flag="0" />
<psa03 value="0.0016" flag="0" />
<psa10 value="0.0004" flag="0" />
<psa30 value="0.0001" flag="0" />
</comp>
<comp name="HHN">
<acc value="0.0040" flag="0" />
<vel value="0.0006" flag="0" />
<psa03 value="0.0014" flag="0" />
<psa10 value="0.0003" flag="0" />
<psa30 value="0.0001" flag="0" />
</comp>
<comp name="HHZ">
<acc value="0.0027" flag="0" />
<vel value="0.0004" flag="0" />
<psa03 value="0.0014" flag="0" />
<psa10 value="0.0004" flag="0" />
<psa30 value="0.0001" flag="0" />
</comp>
</station>
<station code="GR2" name="GRIFFITH OBSERVATORY" insttype="TriNet" lat="34.1183" lon="-118.2994" source="SCSN and TriNet" commtype="DIG">
<comp name="HHE">
<acc value="0.0364" flag="0" />
<vel value="0.0024" flag="0" />
<psa03 value="0.0007" flag="0" />
<psa10 value="0.0001" flag="0" />
<psa30 value="0.0000" flag="0" />
</comp>
<comp name="HHN">
<acc value="0.0247" flag="0" />
<vel value="0.0014" flag="0" />
<psa03 value="0.0005" flag="0" />
<psa10 value="0.0001" flag="0" />
<psa30 value="0.0000" flag="0" />
</comp>
<comp name="HHZ">
<acc value="0.0183" flag="0" />
<vel value="0.0039" flag="0" />
<psa03 value="0.0130" flag="0" />
<psa10 value="0.0006" flag="0" />
<psa30 value="0.0001" flag="0" />
</comp>
</station>
<station code="GRF" name="GRIFFITH PARK OBSERV" insttype="TriNet" lat="34.1192" lon="-118.3004" source="SCSN and TriNet" commtype="DIG">
<comp name="HLE">
<acc value="0.0597" flag="G" />
<vel value="0.0157" flag="G" />
<psa03 value="0.0464" flag="G" />
<psa10 value="0.0111" flag="G" />
<psa30 value="0.0010" flag="G" />
</comp>
<comp name="HLN">
<acc value="0.0471" flag="G" />
<vel value="0.0113" flag="G" />
<psa03 value="0.0264" flag="G" />
<psa10 value="0.0062" flag="G" />
<psa30 value="0.0008" flag="G" />
</comp>
<comp name="HLZ">
<acc value="0.0203" flag="G" />
<vel value="0.0050" flag="G" />
<psa03 value="0.0182" flag="G" />
<psa10 value="0.0029" flag="G" />
<psa30 value="0.0005" flag="G" />
</comp>
</station>
<station code="GSC" name="GOLDSTONE" insttype="TriNet" lat="35.30176" lon="-116.80572" source="SCSN and TriNet" commtype="DIG">
<comp name="HHE">
<acc value="0.0027" flag="0" />
<vel value="0.0022" flag="0" />
<psa03 value="0.0067" flag="0" />
<psa10 value="0.0028" flag="0" />
<psa30 value="0.0002" flag="0" />
</comp>
<comp name="HHN">
<acc value="0.0031" flag="0" />
<vel value="0.0020" flag="0" />
<psa03 value="0.0067" flag="0" />
<psa10 value="0.0026" flag="0" />
<psa30 value="0.0002" flag="0" />
</comp>
<comp name="HHZ">
<acc value="0.0024" flag="0" />
<vel value="0.0017" flag="0" />
<psa03 value="0.0048" flag="0" />
<psa10 value="0.0039" flag="0" />
<psa30 value="0.0002" flag="0" />
</comp>
</station>
<station code="HEC" name="HECTOR" insttype="TriNet" lat="34.8294" lon="-116.335" source="SCSN and TriNet" commtype="DIG">
<comp name="HHE">
<acc value="0.0027" flag="0" />
<vel value="0.0018" flag="0" />
<psa03 value="0.0062" flag="0" />
<psa10 value="0.0050" flag="0" />
<psa30 value="0.0003" flag="0" />
</comp>
<comp name="HHN">
<acc value="0.0020" flag="0" />
<vel value="0.0019" flag="0" />
<psa03 value="0.0063" flag="0" />
<psa10 value="0.0023" flag="0" />
<psa30 value="0.0002" flag="0" />
</comp>
<comp name="HHZ">
<acc value="0.0016" flag="0" />
<vel value="0.0010" flag="0" />
<psa03 value="0.0033" flag="0" />
<psa10 value="0.0018" flag="0" />
<psa30 value="0.0001" flag="0" />
</comp>
</station>
<station code="HLN" name="HIGHLAND" insttype="TriNet" lat="34.12128" lon="-117.21897" source="SCSN and TriNet" commtype="DIG">
<comp name="HLE">
<acc value="0.0104" flag="G" />
<vel value="0.0063" flag="G" />